server:
  port: 8071


--- # xxl-job ??
xxl.job:
  # ?????
  enabled: true
  # ?????????????????????????????
  admin-addresses: http://localhost:8090/xxl-job-admin
  # ?????TOKEN??????
  access-token: xxl-job
  executor:
    # ???AppName??????????????????????
    appname: xxl-job-executor-sample
    # ?????? ????9101?????
    port: 9106
    # ????????IP:PORT
    #    address: 127.0.0.1:9101
    # ???IP???????IP
    #    ip: 127.0.0.1
    # ???????????????
    logpath: ./logs/xxl-job
    # ??????????????3??
    logretentiondays: 30







